#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Merges scripts/parts/*.py into military_data.py and civil_extra.py.

Each part file exports ROWS. Military parts use MIL_COLS (26 fields), civil
parts use CIVIL_COLS (24). Rows already present in the hand-written table in
build_data.py — matched on id and on manufacturer+model — are dropped, so a
part file can safely overlap with another.
"""
import importlib, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "parts"))

MIL_PARTS = ["mil_prop_allied", "mil_prop_axis", "mil_bombers", "mil_transport",
             "mil_jet_west", "mil_jet_east", "mil_trainers_iran",
             "rotary_mil", "uav"]
CIV_PARTS = ["civ_classic", "civ_jets", "civ_rotary"]


def load(mods, width):
    rows = []
    for m in mods:
        mod = importlib.import_module(m)
        for r in mod.ROWS:
            assert len(r) == width, (m, r[0], len(r))
            rows.append(r)
    return rows


def dedupe(rows, ids, names):
    out = []
    for r in rows:
        nk = (r[1].lower(), r[2].lower())
        if r[0] in ids or nk in names:
            continue
        ids.add(r[0]); names.add(nk); out.append(r)
    return out


def dump(path, name, rows):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("# Generated by scripts/merge_parts.py from scripts/parts/*.py"
                " — do not hand-edit.\n")
        f.write("N = None\n\n%s = [\n" % name)
        for r in rows:
            f.write(repr(tuple(r)).replace("None", "N") + ",\n")
        f.write("]\n")


def main():
    import build_data as bd
    ids = {r[0] for r in bd.BASE_CIVIL_ROWS}
    names = {(r[1].lower(), r[2].lower()) for r in bd.BASE_CIVIL_ROWS}
    mil = dedupe(load(MIL_PARTS, 26), ids, names)
    civ = dedupe(load(CIV_PARTS, 24), ids, names)
    dump(os.path.join(HERE, "military_data.py"), "MIL_ROWS", mil)
    dump(os.path.join(HERE, "civil_extra.py"), "CIVIL_ROWS_EXTRA", civ)
    print(f"merged {len(mil)} military + {len(civ)} civil extra rows")


if __name__ == "__main__":
    main()
