# -*- coding: utf-8 -*-
EN = {
 "atr-42-600": ("", "", "An updated ATR 42 with a new cabin and glass avionics that burns less fuel."),
 "atr-42-500": ("", "", "Short-haul turboprop with low operating costs."),
 "atr-72-500": ("", "", "The generation before the -600, with older avionics."),
 "atr-72-600": ("", "", "Iran Air took delivery of several airframes after the JCPOA."),
 "airbus-a220-100": ("", "", "The Bombardier CSeries design that Airbus acquired."),
 "airbus-a220-300": ("", "", "Its fuel efficiency in the 130-seat class is unmatched."),
 "airbus-a300-600r": ("", "", "Widely used by Iran Air and Mahan Air."),
 "airbus-a300b2": ("", "", "The A300B2 was the world's first twin-engine widebody, and Iran Air was among its earliest operators in Asia."),
 "airbus-a300b4": ("", "", "The world's first twin-engine widebody and the first Airbus product."),
 "airbus-a310-200": ("", "", "The A310-200 was built with a shortened A300 fuselage and a new wing, and its flight deck was worked by just two pilots."),
 "airbus-a310-300": ("", "", "The first Airbus with a two-crew flight deck; flown by Iran Air and Mahan Air."),
 "airbus-a318": ("", "", "The smallest member of the A320 family, certified for steep-approach runways."),
 "airbus-a319": ("", "", "A shortened A320 with long range."),
 "airbus-a319neo": ("", "", "The smallest member of the neo family with new fuel-efficient engines, though its orders have fallen far short of the A320 and A321."),
 "airbus-a320-200": ("", "", "The first airliner with fly-by-wire controls and a sidestick."),
 "airbus-a320neo": ("", "", "About 15 percent lower fuel burn than the ceo generation."),
 "airbus-a321-200": ("", "", "The longest member of the ceo generation."),
 "airbus-a321lr": ("", "", "With extra fuel tanks, the A321LR made transatlantic flights economical on a narrowbody."),
 "airbus-a321xlr": ("", "", "With an integral fuselage fuel tank, the A321XLR has the greatest range of any current narrowbody."),
 "airbus-a321neo": ("", "", "The LR and XLR versions extend range to 8,700 km."),
 "airbus-a330-200": ("", "", "In the Mahan Air and Iran Air fleets."),
 "airbus-a330-200f": ("", "", "The A330 freighter was built with a redesigned nose gear so the cabin floor stays level on the ground."),
 "airbus-a330-300": ("", "", "The stretched, higher-capacity A330."),
 "airbus-a330-800neo": ("", "", "The slowest-selling neo version, but with the family's longest range."),
 "airbus-a330-900neo": ("", "", "A new wing with sharklets and an Airspace cabin."),
 "airbus-a340-200": ("", "", "The shortest A340 had very long range, but fewer than thirty were built."),
 "airbus-a340-300": ("", "", "A four-engine jet for routes without ETOPS coverage."),
 "airbus-a340-500": ("", "", "The A340-500 was for years the longest-range airliner in the world, flying nonstop from Singapore to New York."),
 "airbus-a340-600": ("", "", "It was the world's longest airliner until the 747-8 arrived; Mahan Air operates it."),
 "airbus-a350-1000": ("", "", "Six-wheel main landing gear for the higher weight."),
 "airbus-a350-900": ("", "", "Composite fuselage and wing; a direct rival to the 787 and 777."),
 "airbus-a350f": ("", "", "The A350 freighter, with a composite fuselage and the largest cargo door in the world, takes on the 777F."),
 "airbus-a380-800": ("", "", "The world's largest airliner, with two full decks."),
 "airspeed-ambassador": ("", "", "This high-wing airliner with a triple tail flew with BEA as the Elizabethan and had a remarkably quiet cabin."),
 "antonov-an-140": ("", "", "Assembled by HESA as the IrAn-140; it no longer flies."),
 "antonov-an-148": ("", "", "A high-wing regional jet for rough runways."),
 "antonov-an-24": ("", "", "It was the workhorse of Eastern Bloc regional routes and could operate from unpaved fields and cold Siberian airports."),
 "avro-rj70": ("", "", "The RJ70 was the smallest member of the family, and only twelve were built, the fewest of any variant."),
 "avro-rj85": ("", "", "The RJ85 was a modernized 146 with new engines and a new flight deck, and served mostly in Europe."),
 "avro-york": ("", "", "It mated a new fuselage to the wing of the Lancaster bomber and played a major part in the Berlin Airlift and on Empire routes."),
 "concorde": ("", "", "The only successful supersonic airliner in history; Mach 2.04."),
 "bac-one-eleven-500": ("", "", "The One-Eleven became Britain's best-selling jet airliner, and the 500 had a stretched fuselage for more capacity."),
 "beechcraft-1900d": ("", "", "It is the best-selling nineteen-seat airliner in the world, and its stand-up cabin was a key advantage over rivals."),
 "boeing-247": ("", "", "The world's first modern airliner, with an all-metal cantilever wing and retractable landing gear, it transformed aircraft design."),
 "boeing-307": ("", "", "It was the world's first airliner with a pressurized cabin, which let it fly above most storms."),
 "boeing-377": ("", "", "This double-deck giant, with a lower-deck lounge and berths, offered the most luxurious air travel of the piston era on ocean routes."),
 "boeing-707-120": ("", "", "The first 707 version, powered by turbojets, opened the jet age in American commercial aviation in 1958."),
 "boeing-707-320b": ("", "", "The world's first best-selling jet airliner; Iran Air and Saha Air operated it for years."),
 "boeing-707-320c": ("", "", "The convertible 320C, with a large cargo door, carried both passengers and freight, and Iran Air used it for years."),
 "boeing-717-200": ("", "", "The last survivor of the DC-9 line; production ended in 2006."),
 "boeing-720b": ("", "", "The 720B was a lighter, shorter 707 for medium-haul routes, and Iran Air put it into service in the 1960s."),
 "boeing-727-100": ("", "", "The first 727 version, with three rear-mounted engines and high-lift wings, allowed operations from short runways."),
 "boeing-727-200": ("", "", "A trijet with tail-mounted engines; it flew in the Iran Air fleet until the late 2010s."),
 "boeing-737-max-10": ("", "", "The longest 737, with telescoping landing gear."),
 "boeing-737-max-7": ("", "", "The shortest MAX, with the family's longest range."),
 "boeing-737-max-8": ("", "", "The best-selling member of the MAX family; grounded for 20 months after two crashes."),
 "boeing-737-max-9": ("", "", "The replacement for the 737-900ER."),
 "boeing-737-100": ("", "", "The shortest member of the 737 family; only 30 were built."),
 "boeing-737-200": ("", "", "The version that made the 737 a worldwide success; able to land on unpaved runways."),
 "boeing-737-300": ("", "", "The start of the Classic generation, with high-bypass engines and oval intakes."),
 "boeing-737-400": ("", "", "The stretched Classic; flown in Iran in both passenger and freighter roles."),
 "boeing-737-500": ("", "", "A direct replacement for the 737-200 with greater range."),
 "boeing-737-600": ("", "", "The slowest-selling member of the NG generation."),
 "boeing-737-700": ("", "", "The baseline of the NG generation and a mainstay at Southwest."),
 "boeing-737-800": ("", "", "The best-selling narrowbody in history before the MAX; in the fleets of several Iranian carriers."),
 "boeing-737-900": ("", "", "The 737-900 was the longest of the Next Generation, but few were built because it lacked an additional emergency exit."),
 "boeing-737-900er": ("", "", "The longest NG-generation 737, with additional emergency exits."),
 "boeing-747-100": ("", "", "The world's first widebody and the start of the jumbo-jet era."),
 "boeing-747-100sr": ("", "", "This short-range 747 was built for Japan's high-density domestic market, with a structure strengthened for frequent takeoffs and landings."),
 "boeing-747-200b": ("", "", "The backbone of Iran Air's long-haul flights in the 1970s and 1980s."),
 "boeing-747-300": ("", "", "The first 747 with a stretched upper deck."),
 "boeing-747-400": ("", "", "The best-selling 747, with winglets and a two-crew flight deck."),
 "boeing-747-400er": ("", "", "The long-range 747-400 was built only to a Qantas order and carried an extra fuel tank in the cargo hold."),
 "boeing-747-400f": ("", "", "The 747-400 freighter, with a swing-up nose and without the long upper-deck hump, became the backbone of the world's air-cargo fleet."),
 "boeing-747-8i": ("", "", "The world's longest airliner; production ended in 2023."),
 "boeing-747-8f": ("", "", "The 747-8F is the largest and last of the jumbo-jet generation, and its payload exceeds that of any other Western commercial aircraft."),
 "boeing-747sp": ("", "", "A shortened, ultra-long-range version; Iran Air was one of its best-known operators."),
 "boeing-757-200": ("", "", "A narrowbody with exceptional climb performance; popular on transoceanic flights."),
 "boeing-757-200pf": ("", "", "The 757 freighter was built without windows and with a large cargo door, and most of the fleet belongs to UPS."),
 "boeing-757-300": ("", "", "Boeing's longest narrowbody."),
 "boeing-767-200er": ("", "", "The first twinjet to make ETOPS flights across the Atlantic routine."),
 "boeing-767-300er": ("", "", "The best-selling 767; its freighter line is still running."),
 "boeing-767-300f": ("", "", "The 767-300F is the world's most widely used medium-haul freighter, and the big parcel carriers have placed repeat orders for it."),
 "boeing-767-400er": ("", "", "The longest 767, with raked wingtips."),
 "boeing-777-200er": ("", "", "The first aircraft designed entirely by computer."),
 "boeing-777-200lr": ("", "", "Holder of the record for the longest nonstop flight by an airliner."),
 "boeing-777-300er": ("", "", "The best-selling twin-engine widebody; the mainstay of the Emirates fleet."),
 "boeing-777-8": ("", "", "The 777-8 is the shorter, longer-range member of the 777X family, and its folding wings let it use conventional terminals."),
 "boeing-777-9": ("", "", "The world's longest airliner, with folding wingtips."),
 "boeing-777f": ("", "", "The 777F is the world's best-selling long-range twin-engine freighter, and its fuel efficiency displaced the four-engine generation."),
 "boeing-787-10": ("", "", "The longest Dreamliner, with less range."),
 "boeing-787-8": ("", "", "The first airliner with a largely composite fuselage."),
 "boeing-787-9": ("", "", "The best-selling Dreamliner."),
 "bombardier-crj1000": ("", "", "The longest CRJ built."),
 "bombardier-crj200": ("", "", "Based on the Challenger business jet; it has also been used in Iran."),
 "bombardier-crj550": ("", "", "The CRJ550 came from converting the CRJ700 and was offered for the US market with fifty seats and more baggage space."),
 "bombardier-crj700": ("", "", "A redesigned wing and a taller cabin."),
 "bombardier-crj900": ("", "", "The most popular second-generation CRJ."),
 "bristol-britannia": ("", "", "Its uncommonly quiet cabin earned it the nickname Whispering Giant, but production delays made it a casualty of the jet age."),
 "bae-146-200": ("", "", "The BAe 146 became known as the quiet jet for its very low noise and was widely used at mountain airports."),
 "bae-146-300": ("", "", "A quiet four-engine jet; well suited to city airports."),
 "bae-jetstream-31": ("", "", "This British nineteen-seater sold well in the American feeder-airline market during the 1980s."),
 "bae-jetstream-41": ("", "", "A stretched Jetstream with twenty-nine seats, whose production was cut short by the slump in the regional market."),
 "britten-norman-islander": ("", "", "Simple and inexpensive, it has flown on islands and very short routes around the world for more than half a century."),
 "comac-arj21-700": ("", "", "China's first jet airliner."),
 "comac-c919": ("", "", "China's rival to the A320neo and 737 MAX."),
 "convair-880": ("", "", "The Convair 880 was the fastest jet airliner of its day, but its narrow fuselage and high fuel burn limited sales."),
 "convair-990": ("", "", "With anti-shock bodies on its wing, the Coronado was the fastest subsonic airliner in history, but it cost Convair heavy financial losses."),
 "convair-cv-240": ("", "", "This pressurized twin was designed to succeed the DC-3 and brought greater comfort to short domestic routes."),
 "convair-cv-440": ("", "", "It was the most advanced piston version of the Convairliner family, offered with a quieter cabin and more powerful engines."),
 "dehavilland-dash8-q400": ("", "", "The fastest airliner turboprop in widespread service."),
 "dehavilland-dash8-300": ("", "", "The mid-size member of the Dash 8 family."),
 "dornier-228": ("", "", "Its new-technology wing and rugged landing gear make it well suited to mountainous regions and rough strips."),
 "dornier-328": ("", "", "It was one of the fastest regional turboprops, and its cabin offered comfort close to that of a jet."),
 "douglas-dc-2": ("", "", "It was Douglas's answer to the Boeing 247, and with a larger fuselage and fourteen seats it secured the company's position."),
}
