# -*- coding: utf-8 -*-
EN = {
 "douglas-dc-3": ("", "", "The most famous piston airliner in history, the first to make air transport profitable, and Iranian airlines operated it as well."),
 "douglas-dc-4": ("", "", "Douglas's first four-engine airliner with tricycle landing gear, it popularized ocean crossings after the war."),
 "douglas-dc-6b": ("", "", "The pure passenger version of the DC-6 family, it became very popular thanks to its fuel economy and high reliability."),
 "douglas-dc-7c": ("", "", "The last and most ambitious Douglas piston airliner, it made non-stop flights across the Atlantic possible."),
 "douglas-dc-8-32": ("", "", "The DC-8 Series 30 was the intercontinental version with more powerful engines and was a direct rival to the Boeing 707."),
 "douglas-dc-8-63": ("", "", "With its stretched fuselage and improved wing, the DC-8-63 was the highest-capacity narrowbody jet of the 1960s."),
 "embraer-e170": ("", "", "A 2+2 cabin with no middle seat."),
 "embraer-e175": ("", "", "The most widely used regional jet in North America."),
 "embraer-e175-e2": ("", "", "The E175-E2 has waited years to enter service because of the weight limits in US pilot scope clauses."),
 "embraer-e190": ("", "", "It has flown in Iran as well."),
 "embraer-e190-e2": ("", "", "A new wing and geared turbofan engines."),
 "embraer-e195": ("", "", "The longest first-generation E-Jet."),
 "embraer-e195-e2": ("", "", "Embraer's largest airliner."),
 "embraer-emb-110": ("", "", "Embraer's first mass-produced aircraft, it laid the foundation of Brazil's aviation industry and its entry into the world market."),
 "embraer-emb-120": ("", "", "A fast 30-seat Brazilian turboprop that held an important place in the US regional network in the 1990s."),
 "embraer-erj-135": ("", "", "The ERJ 135 was a shortened 37-seat version of the 145 and flew mostly on US feeder routes."),
 "embraer-erj-140": ("", "", "The ERJ 140 was the middle member of the family and was built solely to answer the limits of US pilot scope clauses."),
 "embraer-erj-145": ("", "", "A narrow regional jet with 1+2 seating."),
 "fairchild-metro-iii": ("", "", "Its very slim fuselage earned it the nickname cigar tube, and today it is used mostly for light cargo and mail."),
 "fokker-70": ("", "", "The Fokker 70 was a shortened Fokker 100, and only a small number were built before the company went bankrupt."),
 "fokker-f28": ("", "", "The predecessor of the Fokker 100, suited to short runways."),
 "fokker-100": ("", "", "For years the backbone of Iran Air's domestic flights."),
 "fokker-50": ("", "", "A modernized F27 with modern turboprop engines."),
 "ford-trimotor": ("", "", "This all-metal trimotor with corrugated skin is regarded as one of the first icons of commercial air travel in America."),
 "handley-page-herald": ("", "", "It was first designed with four piston engines, and the late switch to turboprops cost it the chance to compete with Fokker."),
 "handley-page-hermes": ("", "", "It was Britain's attempt to compete with American airliners, but small numbers and a short life left it with little impact."),
 "harbin-y-12": ("", "", "A Chinese high-wing light aircraft with short-field takeoff capability that has sold in developing markets."),
 "hs-748": ("", "", "It was built to work from dirt strips in demanding conditions and was also produced under licence in India."),
 "hawker-siddeley-trident-1c": ("", "", "The Trident was the first aircraft to perform a fully automatic landing in zero visibility in commercial service."),
 "ilyushin-il-12": ("", "", "The first modern Soviet twin-engine airliner after the war, it took over from the Lisunov Li-2 at Aeroflot."),
 "ilyushin-il-62m": ("", "", "The largest airliner with four tail-mounted engines."),
 "ilyushin-il-86": ("", "", "The Il-86 was the first Soviet widebody, and passengers boarded the cabin by the aircraft's own built-in airstairs."),
 "ilyushin-il-96-300": ("", "", "A Russian four-engine widebody; production was very limited."),
 "ilyushin-il-96-400t": ("", "", "The Il-96-400T is the freighter version with a stretched fuselage and more powerful engines, and only a small number have been built."),
 "irkut-mc-21-300": ("", "", "The MC-21 is the first Russian narrowbody with a composite wing and has the widest cabin in its class."),
 "let-l-410": ("", "", "It is the most widely used light regional aircraft in Eastern Europe and is still built and refurbished in the Czech Republic."),
 "lisunov-li-2": ("", "", "A Soviet-built copy of the Douglas DC-3 with domestic engines, it became the backbone of Aeroflot in the 1940s and 1950s."),
 "lockheed-l-049": ("", "", "Its curved fuselage and triple tail make it one of the most beautiful aircraft in history, and it had a pressurized cabin."),
 "lockheed-l-1049": ("", "", "A stretched Constellation with turbo-compound engines, it was the main rival to the DC-7 in the 1950s."),
 "lockheed-l-1649": ("", "", "The last member of the Constellation family had an all-new wing and unprecedented range, but the arrival of jets cut its life short."),
 "lockheed-l-188": ("", "", "It was the only large American turboprop airliner, and its reputation suffered after two crashes caused by wing flutter."),
 "martin-2-0-2": ("", "", "It was the first post-war American airliner to receive a type certificate, but a wing structural problem limited its sales."),
 "martin-4-0-4": ("", "", "The stretched and pressurized Martin flew for years alongside the Convairs on American local service routes."),
 "mcdonnell-douglas-dc-10-10": ("", "", "The first DC-10 version was built for US domestic routes, with its third engine mounted on the tail."),
 "douglas-dc-10-30": ("", "", "A widebody trijet with an engine mounted in the vertical fin."),
 "douglas-dc-9-30": ("", "", "The basis of a family that ran all the way to the Boeing 717."),
 "mcdonnell-douglas-dc-9-50": ("", "", "It was the longest DC-9 variant, and its experience fed directly into the design of the MD-80 family."),
 "mcdonnell-md-11": ("", "", "The DC-10's successor; today mostly a freighter."),
 "mcdonnell-douglas-md-11f": ("", "", "After the passenger market declined the MD-11F became the type's most successful role, and FedEx was its largest operator."),
 "mcdonnell-md-82": ("", "", "For years the backbone of Iran's domestic fleet, popularly known as the Madoodi."),
 "mcdonnell-md-83": ("", "", "A longer-range MD-80 with an additional fuel tank."),
 "mcdonnell-douglas-md-87": ("", "", "The MD-87 was the shortest member of the MD-80 family and had more range than the other variants."),
 "mcdonnell-douglas-md-88": ("", "", "The MD-88 was introduced with a glass cockpit and a new navigation system, and Delta was its largest operator."),
 "mcdonnell-md-90-30": ("", "", "An MD-80 with new engines; the last independent McDonnell Douglas design."),
 "namc-ys-11": ("", "", "It was the only Japanese-built airliner after the Second World War to reach mass production and export."),
 "saab-2000": ("", "", "It was the fastest Western turboprop airliner, but its high cost and competition from regional jets cut production short."),
 "saab-340b": ("", "", "A light regional turboprop."),
 "shorts-330": ("", "", "Its boxy fuselage and braced high wing gave it an unusual look, but it offered good load capacity."),
 "shorts-360": ("", "", "A stretched Shorts 330 with a single fin, which improved its aerodynamics and passenger capacity."),
 "sud-aviation-caravelle-3": ("", "", "The Caravelle was the world's first short-haul jet airliner and introduced rear-fuselage engine mounting to the industry."),
 "sukhoi-ssj100": ("", "", "Russia's first modern civil airliner, developed with Western cooperation."),
 "tupolev-tu-104": ("", "", "The Tu-104 was the world's second operational jet airliner and for a time the only jet airliner in service."),
 "tupolev-tu-114": ("", "", "It was the largest and fastest turboprop airliner in history, and its contra-rotating propellers linked Moscow with Havana."),
 "tupolev-tu-124": ("", "", "The Tu-124 was a scaled-down Tu-104 and is regarded as the world's first turbofan-powered airliner."),
 "tupolev-tu-134": ("", "", "Early variants had a glazed nose."),
 "tupolev-tu-144": ("", "", "The Tu-144 was the world's first supersonic airliner, but its commercial service stayed very short and accident-ridden."),
 "tupolev-tu-154m": ("", "", "A Russian trijet that flew in Iranian fleets for many years."),
 "tupolev-tu-204-100": ("", "", "The Russian answer to the Boeing 757."),
 "tupolev-tu-204-300": ("", "", "The Tu-204-300 is the shortened, long-range member of the family and was designed for the long routes across Siberia."),
 "tupolev-tu-214": ("", "", "The Tu-214 is the heavier member of the Tu-204 family and has been restarted in limited production at the Kazan plant."),
 "vickers-viking": ("", "", "Derived from the Wellington bomber, it was Britain's first post-war airliner for European routes."),
 "vickers-vc10": ("", "", "The VC10 was designed for the short, hot runways of Africa, and its four engines sat at the rear of the fuselage."),
 "vickers-vanguard": ("", "", "It was the high-capacity successor to the Viscount, but it arrived just as jets were becoming widespread and sold poorly."),
 "vickers-viscount-800": ("", "", "It was the world's first turboprop airliner, and Iran Air also had several of them in its fleet."),
 "xian-ma60": ("", "", "It is a Chinese development of the Antonov An-24 and has been exported mostly to Asian and African countries on easy credit terms."),
 "yakovlev-sj-100": ("", "", "The new Superjet is a fully localized version in which Western parts and engines have been replaced by Russian-built ones."),
 "yakovlev-yak-40": ("", "", "The Yak-40 was the world's first regional jet and could land on short dirt strips."),
 "yakovlev-yak-42d": ("", "", "A medium-haul trijet; it has been operated in Iran."),
 "de-havilland-comet-1": ("", "", "The Comet was the world's first jet airliner and was withdrawn after several crashes caused by metal fatigue in the fuselage."),
 "de-havilland-comet-4": ("", "", "With a strengthened fuselage, the Comet 4 made the first transatlantic jet airliner flight in October 1958."),
 "dh-dove": ("", "", "It was one of Britain's most successful post-war light aircraft and was used for local airline routes and executive flights."),
 "dh-heron": ("", "", "It was a larger, four-engine version of the Dove, built to fly from short and remote airstrips."),
 "dhc-6-twin-otter": ("", "", "Its short-field performance and the option of skis or floats have made it a favourite in polar and island regions."),
 "dhc-7-dash-7": ("", "", "With four engines and a large wing it could take off quietly from very short city airstrips."),
 "aidc-at-3": ("Advanced jet trainer", "A 20 mm cannon pod plus bombs and rockets", "The AT-3 is Taiwan's indigenous advanced trainer and is flown by the country's air force display team."),
 "aidc-f-ck-1": ("Lightweight air defence fighter", "One 20 mm cannon and Tien Chien missiles", "The Ching-kuo was designed after fighter sales to Taiwan were restricted, to meet the island's air defence needs."),
 "aeritalia-g-222": ("Tactical transport", "Unarmed; 53 troops or 9 tonnes of cargo", "An Italian tactical transport that became the basis for the C-27 Spartan and was also used on firefighting missions."),
 "aermacchi-mb-326": ("Jet trainer and light attack", "Six hardpoints for up to 1800 kg in the attack version", "This Italian jet trainer was also built under licence and exported in South Africa, Brazil and Australia."),
 "aermacchi-mb-339": ("Advanced jet trainer", "Six hardpoints for up to 1815 kg", "The successor to the MB-326, with a stepped cockpit, it has for years been the mount of Italy's Frecce Tricolori display team."),
 "aero-l-159a": ("Light attack fighter", "A 20 mm cannon pod plus missiles and guided bombs", "The L-159 is the single-seat combat version of the Albatros with a Western radar, built for light attack and close air support."),
 "aero-l-29": ("Basic jet trainer", "A cannon pod and rockets on two underwing stations", "The L-29 Delfin was the standard trainer of the Warsaw Pact countries and more than three thousand were built."),
 "aero-l-39-albatros": ("Advanced trainer and light attack", "Four hardpoints for up to 1100 kg", "The Albatros is the most-produced jet trainer in the world and still flies with dozens of air forces and display teams."),
 "aero-l-39c": ("Advanced jet trainer", "A cannon pod, rockets and light bombs", "The L-39 Albatros is the most numerous jet trainer in the world and still flies with air forces and display teams."),
 "aichi-d3a": ("Carrier dive bomber", "Three 7.7 mm machine guns and up to 370 kg of bombs", "With its fixed landing gear the Val was Japan's premier dive bomber and went after Allied warships."),
 "airbus-a330-mrtt": ("Multirole tanker and transport", "Unarmed; 111 tonnes of fuel or 300 troops", "A European tanker that, with no additional tanks, both refuels aircraft and moves troops and patients."),
 "airbus-a400m": ("Tactical and strategic transport", "Unarmed; 116 troops or 37 tonnes of cargo", "A European transport with the most powerful Western turboprop engine, filling the gap between the Hercules and the Boeing C-17."),
 "airbus-c-295": ("Tactical transport", "Unarmed; 71 troops or 9.2 tonnes of cargo", "A stretched and more powerful CN-235 that has become Europe's best-selling light tactical transport."),
 "albatros-d-iii": ("Biplane fighter", "Two 7.92 mm Spandau machine guns", "The Albatros D.III was Germany's mainstay during Bloody April 1917, though its lower wing sometimes failed."),
 "antonov-an-12": ("Tactical transport", "Two 23 mm cannon in a tail turret; 20 tonnes of cargo", "The Soviet counterpart to the Hercules, with a tail gun turret, still flying in cargo fleets across Africa and Asia."),
 "antonov-an-124": ("Ultra-heavy strategic transport", "Unarmed; 150 tonnes of cargo", "The world's largest series-produced freighter, moving outsized loads through two large nose and tail doors."),
 "antonov-an-2": ("Utility and light transport", "Unarmed; 12 passengers or 1.5 tonnes of cargo", "The largest mass-produced single-engine biplane in the world, it flies at very low speed and is still in service."),
 "antonov-an-22": ("Ultra-heavy strategic transport", "Unarmed; 80 tonnes of cargo", "The heaviest turboprop aircraft in the world, with contra-rotating propellers, built to carry tanks and missiles."),
 "antonov-an-225": ("Special outsize heavy-lift transport", "Unarmed; 250 tonnes of cargo", "The heaviest aircraft ever built, of which only one flew, and it was destroyed in 2022."),
 "antonov-an-26": ("Light tactical transport", "Unarmed; 40 troops or 5.5 tonnes of cargo", "The cargo version of the An-24 with a sliding rear ramp, one of the most numerous light military transports in the world."),
 "antonov-an-32": ("High-altitude tactical transport", "Unarmed; 50 troops or 6.7 tonnes of cargo", "A more powerful An-26 with the engines above the wing, optimized for work at hot and high airfields."),
 "antonov-an-70": ("Heavy tactical transport", "Unarmed; 300 troops or 47 tonnes of cargo", "This transport was designed around fuel-efficient propfan engines, but political and financial crises prevented series production."),
 "avia-b534": ("Biplane fighter", "Four 7.92 mm machine guns", "It was one of the finest biplane fighters in the world, but its country fell under German occupation before it could be put to use."),
 "avro-lancaster-b1": ("Heavy night bomber", "Eight 7.7 mm machine guns and up to 6350 kg of bombs", "The Lancaster was the backbone of Britain's night bombing campaign and the only aircraft to carry the special Tallboy and Grand Slam bombs."),
 "avro-vulcan-b2": ("Delta-wing strategic bomber", "A nuclear bomb or up to 9500 kg of conventional bombs", "With its large delta wing the Vulcan was one of the three V bombers and flew the longest-range bombing raid in history in the Falklands War."),
 "beechcraft-t-34": ("Primary trainer", "Unarmed", "This primary trainer was built on the Bonanza light aircraft and was the foundation of US Navy pilot training for decades."),
 "beechcraft-t-34c": ("Primary turboprop trainer", "Four hardpoints on the light attack T-34C-1 version", "The turboprop Mentor gained more power and altitude with its PT6 engine and still flies with several air forces."),
 "beechcraft-t-6-texan-ii": ("Joint basic trainer", "Unarmed; the AT-6 version is armed", "This aircraft was developed from the Swiss PC-9 and now handles basic training for the US Air Force and Navy."),
 "bell-p-39q-airacobra": ("Low-altitude fighter", "One 37 mm cannon, four 12.7 mm machine guns", "Its engine behind the pilot and tricycle gear made it an unconventional design, and it saw most use on the Eastern Front in Soviet hands."),
 "bell-p-63a-kingcobra": ("Fighter and ground support", "One 37 mm cannon, four 12.7 mm machine guns", "It was the larger and more capable successor to the Airacobra, and almost all of them were delivered to the Soviet Union under Lend-Lease."),
 "beriev-a-50": ("Airborne early warning and control", "Unarmed; a rotating Sword radar", "A Russian AWACS based on the Ilyushin Il-76, several of which were hit and destroyed in the war in Ukraine."),
}
