# -*- coding: utf-8 -*-
"""English text for the rotorcraft and uncrewed records.
Values are (role_en, armament_en, notes_en); "" where the Persian side is empty."""

EN = {
# ---- civil helicopters -----------------------------------------------------
"bell-206b": ("", "", "The best-selling light turbine helicopter ever built, and a common sight in Iran."),
"bell-407": ("", "", "The JetRanger's successor, with a four-blade rotor and a wider cabin."),
"bell-412": ("", "", "A four-blade twin used in Iran for rescue work and medical transfer."),
"robinson-r44": ("", "", "The cheapest way into helicopter flying and the most numerous piston helicopter in the world."),
"robinson-r22": ("", "", "The two-seat trainer most helicopter pilots learn on."),
"robinson-r66": ("", "", "Robinson's first turbine helicopter."),
"airbus-h125": ("", "", "The only helicopter ever to have landed on the summit of Everest."),
"airbus-h135": ("", "", "Quiet on its fenestron tail rotor; Europe's most common air ambulance."),
"airbus-h145": ("", "", "A large cabin with sliding side doors and clamshell doors at the rear."),
"leonardo-aw139": ("", "", "The standard aircraft for moving crews to and from offshore oil platforms."),
"sikorsky-s-76": ("", "", "Designed for the offshore oil market and for corporate transport."),
"sikorsky-s-92": ("", "", "Sikorsky's largest civil helicopter, a workhorse over the North Sea."),
"kamov-ka-32": ("", "", "Coaxial twin rotors; used for firefighting and heavy underslung loads."),
"mil-mi-8t-civil": ("", "", "The civil version of the most-produced helicopter in the world; it still flies in Iran."),
"mdhelicopters-md-902": ("", "", "No tail rotor at all — torque is countered by air blown through the boom."),

# ---- military rotorcraft ---------------------------------------------------
"bell-uh-1h": ("Light transport and medical evacuation", "", "The helicopter of the Vietnam War and its lasting image; Iran operated large numbers."),
"bell-ah-1j": ("Attack helicopter", "", "The twin-engine Cobra; Iran was the largest foreign operator of the AH-1J International."),
"bell-ah-1z": ("Naval attack helicopter", "", "The Cobra's latest generation, with a four-blade composite rotor, for the US Marines."),
"bell-206-oh-58": ("Armed scout", "", "The mast-mounted sight let it observe from behind cover."),
"bell-214a": ("Heavy transport", "", "Designed specifically for Iran and named after Isfahan; it still flies there."),
"boeing-ah-64d": ("Attack helicopter", "", "The Longbow radar above the rotor classifies dozens of targets at once."),
"boeing-ch-47f": ("Heavy transport", "", "Tandem rotors front and rear and no tail rotor; Iran operates the CH-47C."),
"boeing-ch-46": ("Naval transport", "", "The US Marine Corps' workhorse for half a century."),
"sikorsky-uh-60m": ("Tactical transport", "", "The Huey's replacement, designed to keep flying after taking ground fire."),
"sikorsky-mh-60r": ("Anti-submarine and anti-ship", "", "The naval Black Hawk, with dipping sonar and torpedoes."),
"sikorsky-ch-53e": ("Super-heavy transport", "", "The West's heaviest helicopter, with three engines and a seven-blade rotor."),
"sikorsky-ch-53k": ("Super-heavy transport", "", "It carries three times the useful load of the E model."),
"sikorsky-sh-3": ("Anti-submarine", "", "A boat hull for landing on water; Iran has operated it too."),
"mcdonnell-md-500": ("Light armed scout", "", "The egg-shaped fuselage and small size suit it to special operations."),
"bell-boeing-v-22": ("Tiltrotor transport", "", "Its rotors swivel so it lifts like a helicopter and cruises like a turboprop."),
"mil-mi-2": ("Light transport", "", "A numerous light helicopter, most of them built in Poland."),
"mil-mi-6": ("Heavy transport", "", "The first helicopter in the world to exceed 300 km/h."),
"mil-mi-8": ("Medium transport", "", "The most-produced helicopter in history; it flies in Iran as well."),
"mil-mi-17": ("Medium transport", "", "The Mi-8 with more powerful engines, for hot and high conditions."),
"mil-mi-24v": ("Attack helicopter and transport", "", "An attack helicopter that also carries eight soldiers — a combination the West never built."),
"mil-mi-26": ("Super-heavy transport", "", "The heaviest and most powerful production helicopter in the world."),
"mil-mi-28n": ("Attack helicopter", "", "Russia's answer to the Apache, with a tandem cockpit and heavy armour."),
"kamov-ka-27": ("Naval anti-submarine", "", "Coaxial rotors and no tail rotor, to fit a cramped ship's deck."),
"kamov-ka-50": ("Single-seat attack helicopter", "", "The world's only single-pilot attack helicopter, and the only one with an ejection seat."),
"kamov-ka-52": ("Attack helicopter", "", "Side-by-side seating, unlike almost every other attack helicopter."),
"westland-lynx": ("Naval multi-role", "", "It took the world helicopter speed record in 1986 at 400 km/h."),
"westland-sea-king": ("Anti-submarine and rescue", "", "The British Sea King, with home-built engines and avionics."),
"leonardo-aw101": ("Transport and anti-submarine", "", "Three engines and a five-blade rotor, for heavy maritime work."),
"airbus-sa330-puma": ("Tactical transport", "", "The start of a family that runs through to the Super Puma and Caracal."),
"airbus-h225m": ("Combat search and rescue", "", "Air-refuellable, so it can recover downed aircrew deep in hostile territory."),
"airbus-sa342-gazelle": ("Light scout and anti-armour", "", "The first helicopter with a fenestron — a tail rotor enclosed in the fin."),
"airbus-tiger": ("Attack helicopter", "", "A largely composite airframe, to cut weight and radar cross-section."),
"nhindustries-nh90": ("Tactical transport", "", "The first production helicopter with full fly-by-wire control."),
"leonardo-a129": ("Light attack helicopter", "", "The first attack helicopter designed entirely in Europe."),
"airbus-bo-105": ("Light multi-role", "", "The world's first light twin-engine helicopter, and aerobatic with it."),
"airbus-alouette-iii": ("Light multi-role", "", "A mountain workhorse; it holds a landing record above 6,000 metres."),
"changhe-z-10": ("Attack helicopter", "", "China's first wholly indigenous attack helicopter."),
"harbin-z-9": ("Light armed helicopter", "", "The Chinese AS365 Dauphin, built under licence."),
"harbin-z-19": ("Armed scout", "", "A light scout with tandem seating, derived from the Z-9."),
"hal-dhruv": ("Light multi-role", "", "The first indigenous Indian helicopter to reach series production."),
"hal-prachand": ("High-altitude attack helicopter", "", "Designed to fight above 5,000 metres in the Himalayas."),
"kai-kuh-1": ("Tactical transport", "", "South Korea's indigenous transport helicopter, developed with Airbus."),
"hesa-shabaviz-2-75": ("Light transport", "", "A light transport helicopter built by HESA; very little official data has been published."),
"panha-toufan": ("Attack helicopter", "", "An Iranian rebuild and upgrade of the AH-1J; its exact specifications are unpublished."),

# ---- uncrewed aircraft -----------------------------------------------------
"ga-mq-1": ("Reconnaissance and strike", "", "The first uncrewed aircraft that both watched a target and fired at it."),
"ga-mq-9": ("Strike and reconnaissance", "", "Fifteen times the payload of the Predator, and up to 27 hours aloft."),
"ga-mq-1c": ("Army reconnaissance", "", "The US Army version, diesel-powered and able to stay up more than a day."),
"northrop-rq-4": ("Strategic reconnaissance", "", "A wider wingspan than a Boeing 737, cruising at 18 kilometres."),
"lockheed-rq-170": ("Stealth reconnaissance", "", "A stealth flying wing; one was brought down in Iran in 2011."),
"northrop-x-47b": ("Carrier combat demonstrator", "", "The first uncrewed aircraft to land and take off from a carrier by itself."),
"boeing-mq-25": ("Carrier-based tanker", "", "The world's first uncrewed tanker, meant to extend the range of carrier fighters."),
"iai-heron": ("Strategic reconnaissance", "", "Israel's largest drone, with an endurance beyond thirty hours."),
"elbit-hermes-900": ("Tactical reconnaissance", "", "The Hermes 450's successor, with a longer wing and a larger payload."),
"baykar-tb2": ("Tactical reconnaissance and strike", "", "A cheap and widely used drone that changed the arithmetic of several recent conflicts."),
"baykar-akinci": ("Heavy combat drone", "", "Twin-engined, and able to carry air-to-air missiles."),
"tai-anka": ("Medium-altitude reconnaissance", "", "Türkiye's first indigenous drone with satellite control."),
"bae-taranis": ("Stealth combat demonstrator", "", "The British demonstrator for a next generation of combat drones."),
"dassault-neuron": ("Stealth combat demonstrator", "", "A six-nation European project for a stealth combat drone."),
"sukhoi-s-70": ("Heavy combat drone", "", "A heavy Russian flying wing, designed to fly alongside the Su-57."),
"kronshtadt-orion": ("Reconnaissance and strike", "", "Russia's first medium-altitude armed drone."),
"caig-wing-loong-ii": ("Reconnaissance and strike", "", "The export rival to the MQ-9, at a far lower price."),
"casc-ch-5": ("Heavy reconnaissance and strike", "", "The largest of the Rainbow family, with sixty hours of endurance."),
"hongdu-gj-11": ("Stealth combat drone", "", "A Chinese stealth flying wing with an internal weapons bay."),
"hesa-karrar": ("Jet target and strike drone", "", "An Iranian jet-powered drone launched from a rail with a rocket booster."),
"qods-mohajer-6": ("Tactical reconnaissance and strike", "", "The sixth generation of the Mohajer family, with a twin tail and munition hardpoints."),
"qods-ababil-3": ("Tactical reconnaissance", "", "A short-range reconnaissance drone launched by catapult."),
"shahed-129": ("Medium-altitude reconnaissance and strike", "", "A long-endurance Iranian drone with a high-aspect wing; its figures come from official announcements."),
"shahed-149": ("Heavy combat drone", "", "The largest Iranian combat drone announced, with a 21-metre wingspan."),
"iaio-fotros": ("Medium-altitude reconnaissance", "", "A reconnaissance drone with a stated range of 2,000 kilometres."),
"hesa-kaman-22": ("Reconnaissance and strike", "", "The largest multi-role drone unveiled by the Iranian Air Force."),
}
